name: tests

on:
  push:
    branches:
      - master
      - 10.x
      - 9.x
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2]
        laravel: [^9, ^10]
        scout: [^9, ^10]

    name: Test PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - Scout ${{ matrix.scout }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts=${{ matrix.laravel }}" --no-update
          composer require "illuminate/database=${{ matrix.laravel }}" --no-update
          composer require "illuminate/support=${{ matrix.laravel }}" --no-update
          composer require "laravel/scout=${{ matrix.scout }}" --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Run tests
        run: vendor/bin/phpunit --verbose
